Fix PBash MGEF indexing not caching correctly
Also made it *much* faster by only iterating once instead of up to three
times and avoiding the terrible ctypes-based solution:

PS C:\Users\Infernio> py -2 -m timeit -s "from ctypes import cast, POINTER, c_ulong" "cast(b'ABAT', POINTER(c_ulong)).contents.value"
1000000 loops, best of 3: 0.712 usec per loop
PS C:\Users\Infernio> py -2 -m timeit -s "from struct import unpack" "unpack(u'I', b'ABAT')"
10000000 loops, best of 3: 0.0653 usec per loop

PS C:\Users\Infernio> py -3 -m timeit -s "from ctypes import cast, POINTER, c_ulong" "cast(b'ABAT', POINTER(c_ulong)).contents.value"
500000 loops, best of 5: 590 nsec per loop
PS C:\Users\Infernio> py -3 -m timeit -s "from struct import unpack" "unpack(u'I', b'ABAT')"
5000000 loops, best of 5: 60.1 nsec per loop

Note the record.eid.encode(u'ascii') part, not needed in py2 but *is*
needed in py3:

PS C:\Users\Infernio> py -3
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> struct.unpack('I', 'ABAT')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a bytes-like object is required, not 'str'
>>> struct.unpack('I', 'ABAT'.encode(u'ascii'))
(1413562945,)