Hack for patches set - Dialog runs! EEE TTT
TTT - works correctly? Especially:

+    SEFF = MGEFCode('SEFF')

any reason it should not be in class scope?

EEE

++ common initData??

+                    id_exhaustion[longid] = int(time) may raise VE

+                except (IndexError, ValueError):
+                    pass # too few items, we couldn't unpack or int() failed
+

- belongs to gui (should filter the sources) but oblivion/special are in
the way

On a second thought as patches_set is populated in the GUI
the self.srcs are always in the set if they don't exist
anymore (see Mopy/bash/game/oblivion/patcher/special.py)
in Mopy/bash/patcher/patchers/base.py there were if file checks but
here is a classic application of EAFP

Common read from text - note I dropped some GPath calls

Common init and some EAFP

Note CBash ->  self.isActive = (_cobl_main in p_file.loadSet and
                         self.patchFile.p_file_minfos.getVersionFloat(_cobl_main) > 1.65)

so it reset isActive even if no srcs present - regression introduced in
    Dispose of initPatchFile: broken WIP  + Bye autoRe

fields=[1,2,3]
mod,objectIndex,eid,time = fields[:4]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: need more than 3 values to unpack
int('abc',16)
2748
int('abc')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'abc'